#!/bin/bash

# Deploy script for wkearn.github.io

touch timestamp

git stash

git checkout develop

stack exec site clean
stack exec site build

git fetch --all
git checkout master

rsync -a --filter='P _site/'      \
         --filter='P _cache/'     \
         --filter='P .git/'       \
         --filter='P .gitignore'  \
         --filter='P .stack-work' \
         --delete-excluded        \
         _site/ .

git add -A
DATE=`date +%Y-%m-%d\ %H:%M:%S`
git commit -m "Publish $DATE"

git push origin master

git checkout develop
git stash pop
